obj-$(CONFIG_MARLIN2) := marlin.o

marlin-c-objs += marlin_platform.o
marlin-c-objs += slp_mgr.o
marlin-c-objs += mdbg.o
marlin-c-objs += mdbg_ring.o
marlin-c-objs += mdbg_sdio.o
marlin-c-objs += wcn_op.o
marlin-c-objs += rf/rf.o
marlin-c-objs += wcn_parn_parser.o

marlin-objs += $(marlin-c-objs)
